- name: Deploy Flask + MongoDB on Kind
  hosts: all
  tasks:
    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Kind
      shell: |
        curl -Lo kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

    - name: Install Helm
      dnf:
        name: helm
        state: present

    - name: Install MongoDB
      dnf:
        name: mongodb-org
        state: present

    - name: Start MongoDB Service
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: clone app repo and containerize
      git:
        repo: https://github.com/maximweiss57/falsk-for-monitoring-.git
        dest: /root/flask-monitoring

    - name: build docker image 
      shell: docker build -t flask-monitoring /root/flask-monitoring

    - name: Deploy application to KinD cluster
      shell: kind create cluster --name monitoring-cluster
      ignore_errors: yes

    - name: Apply Kubernetes manifests
      shell: |
        kubectl apply -f /root/flask-monitoring/k8s/namespace.yaml
        kubectl apply -f /root/flask-monitoring/k8s/deployment.yaml
        kubectl apply -f /root/flask-monitoring/k8s/service.yaml
      ignore_errors: yes

    - name: Run MongoDB instance
      kubectl:
        inline: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: mongodb
            labels:
              app: mongodb
          spec:
            containers:
            - name: mongodb
              image: mongo:latest
              ports:
              - containerPort: 27017
      register: mongodb_pod
      ignore_errors: yes

    - name: Wait for MongoDB pod to be ready
      kubectl_wait:
        state: pod_present
        name: "{{ mongodb_pod.metadata.name }}"
        namespace: default
        kubeconfig: "~/.kube/kind-config-monitoring-cluster"
      ignore_errors: yes

    - name: Install MetalLB
      kubectl:
        inline: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: metallb-system
    ---
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: metallb-system
        name: memberlist
      data:
        secretkey: QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.1.240-192.168.1.250
      kubeconfig: "~/.kube/kind-config-monitoring-cluster"
      ignore_errors: yes

    - name: Install Nginx Ingress Controller
      helm:
        name: nginx-ingress
        chart_repo: https://charts.bitnami.com/bitnami
        chart: nginx-ingress-controller
        version: 9.1.0
        namespace: kube-system
      ignore_errors: yes

    - name: Create Ingress Resource
      kubectl:
        action: apply
        src: /root/flask-monitoring/k8s/ingress.yaml
        namespace: monitoring-namespace
      ignore_errors: yes
