apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress  
  namespace: monitoring-app          # Name of the Ingress resource   # Namespace where the Ingress belongs
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Annotation specifying the Ingress class
spec:
  rules:
  - host: monitor-ortuser.ort.tamnun.inc  # Host for which the Ingress should route traffic
    http:
      paths:
      - path: /                       # Path for routing traffic
        pathType: Prefix              # Type of path matching
        backend:
          service:
            name: flask-app-service     # Service to route traffic to
            port:
              number:   80             # Port on the service to forward traffic to